version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    networks:
      - mynetwork
    command: ["-nginx.scrape-uri=http://nginx/stub_status"]

networks:
  mynetwork:
    driver: bridge